apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: gateway-svc-22074
  namespace: MendPerformance
  annotations:
    github.com/project-slug: MendPerformance/gateway-svc-22074
spec:
  type: service
  lifecycle: unknown
  owner: mend.io
